### ISSUE TITLE
Model quantization issue

### ISSUE THREAD

**Issue by dsnsabari** [sony/model_optimization#354] opened 2022-08-24 06:40 UTC
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

1.4.0

### OS Platform and Distribution

colab

### Python version

Python 3.7.13

### Describe the issue

```shell
hi team,

I am using the below example for quantize the mobilenet model. 

https://github.com/sony/model_optimization/blob/main/tutorials/example_keras_mobilenet.py


I have installed MCT on colab and tried to convert the mobilenet model.But I am getting the below error. 


``
AssertionError                            Traceback (most recent call last)
<ipython-input-12-224344cd0a84> in <module>
----> 1 target_platform_cap = mct.get_target_platform_capabilities('tensorflow', 'default')

/usr/local/lib/python3.7/dist-packages/model_compression_toolkit/tpc_models/get_target_platform_capabilities.py in get_target_platform_capabilities(fw_name, target_platform_name)
     76     assert fw_name in tpc_dict, f'Framework {fw_name} is not supported'
     77     supported_models_by_fw = tpc_dict.get(fw_name)
---> 78     assert target_platform_name in supported_models_by_fw, f'Target platform model named {target_platform_name} is not' \
     79                                               f' supported for framework {fw_name}'
     80     return tpc_dict.get(fw_name).get(target_platform_name)

AssertionError: Target platform model named default is not supported for framework tensorflow

``
```

### Code to reproduce the issue

```shell
I used the same code in the below link and I placed twenty sample image in the folder for **FolderImageLoader**

https://github.com/sony/model_optimization/blob/main/tutorials/example_keras_mobilenet.py
```

### Log output

```shell
Please help me on solving the issue. I am trying to quantize the pre-trained network in TensorFlow. It would be great if you share with me the running script on colab.
```

**Comment by reuvenperetz** [comment] 2022-08-24 12:01
Hello,
I was trying (unsuccessfully) to reproduce the error you got (see [gist](https://colab.research.google.com/gist/reuvenperetz/0d2807c02295cd5eaad4fb78462ed52d/issue.ipynb), please).
Could you please try it again?

**Comment by dsnsabari** [comment] 2022-08-24 12:19
hello ,

It is working. I am trying to reduce the object detection TensorFlow SSD mobilenet v2 frozen graph. Is it possible to do with sony quantization?

**Comment by reuvenperetz** [comment] 2022-08-24 13:38
Hi @dsnsabari,

MCT products fakely quantized model, meaning that the weights are quantized but kept in float32 data type, and the activations are quantized using FakeQuantization layers.

What you're looking for is currently not supported in our MCT, but we will take your feedback as a feature request and will address it hopefully in future releases.

**Comment by reuvenperetz** [comment] 2022-08-24 13:40
duplicate of #273

**Comment by dsnsabari** [comment] 2022-08-24 13:44
@reuvenperetz Is it possible to quantize the model into float16 format with MCT? I don't want to convert the model into int8 format. 

I want to use MCT to reduce the TensorFlow frozen graph object detection model size.  Please find the sample model.  http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz

**Comment by reuvenperetz** [comment] 2022-08-24 14:34
@dsnsabari Currently, a model's weights are fakely-quantized (FP32 data type). Unfortunately, we do not provide a way to configure the weights data type.

**Comment by dsnsabari** [comment] 2022-08-25 02:31
@reuvenperetz , thank you for the update.

**Closed** 2022-08-25 07:46 UTC

**Comment by dsnsabari** [comment] 2022-08-26 01:56
@reuvenperetz , When I tried to convert my own model. I am getting the below error. I have trained the model on colab and I directly loaded the saved keras model. 

I got the below error while converting the model using the below script. https://colab.research.google.com/gist/reuvenperetz/0d2807c02295cd5eaad4fb78462ed52d/issue.ipynb


```
16 import operator
     17 
---> 18 import torch
     19 from torch import add, flatten, reshape, split, unsqueeze, dropout, sigmoid, tanh, chunk
     20 from torch.nn import Conv2d, ConvTranspose2d, Linear, BatchNorm2d

[/usr/local/lib/python3.7/dist-packages/torch/__init__.py](https://localhost:8080/#) in <module>
    200     if USE_GLOBAL_DEPS:
    201         _load_global_deps()
--> 202     from torch._C import *  # noqa: F403
    203 
    204 # Appease the type checker; ordinarily this binding is inserted by the

RuntimeError: THPDtypeType.tp_dict == nullptr INTERNAL ASSERT FAILED at "../torch/csrc/Dtype.cpp":139, please report a bug to PyTorch.
```
