### ISSUE TITLE
number of representative dataset and num of image data for mix precision performence

### ISSUE THREAD

**Issue by Ming-Ivy** [sony/model_optimization#1013] opened 2024-03-25 02:08 UTC
### Issue Type

Performance

### Source

source

### MCT Version

1.10

### Python version

3.8

### Describe the issue

```shell
Hi,
I have some questions about the representative data 
I notice that def get_representative_dataset(self, representative_dataset_folder: str, n_iter: 10, batch_size: 16) has two parameter n_iter and batch_size, So the number of total representative dataset number is: n_iter mutiple batch_size, in this case is 32, is that right? so my questions are:
1. How the representative dataset collect data? is it randomly or in sequence collect from the representative_dataset_folder?
2. whether the performance will change if I set different n_iter or batch_size? the bigger the better for both?
3. I set the  n_iter=1, batch_size= 2 and set the num_of_images 10,50,100,1000 , theoretically it should be wrong because num_of_images is more than representative_dataset, but the code can run, is it a bug?
configuration = mct.core.CoreConfig(quantization_config,mixed_precision_config=mct.core.MixedPrecisionQuantizationConfigV2(num_of_images=args.mixed_precision_num_of_images))
```

### Code to reproduce the issue

```shell
MixedPrecisionQuantizationConfigV2 =mct.core.MixedPrecisionQuantizationConfigV2(compute_distance_fn=None, 
                                                                                    distance_weighting_method=get_average_weights, 
                                                                                    num_of_images=args.mixed_precision_num_of_images, 
                                                                                    configuration_overwrite=None, 
                                                                                    num_interest_points_factor=1.0, 
                                                                                    use_hessian_based_scores=True, 
                                                                                    norm_scores=True, 
                                                                                    refine_mp_solution=True, 
                                                                                    metric_normalization_threshold=1e10)
    
    my_core_config= mct.core.CoreConfig(mixed_precision_config=MixedPrecisionQuantizationConfigV2)
    import numpy as np
    kpi = mct.KPI(weights_memory=np.inf, activation_memory=np.inf, total_memory=np.inf, bops=np.inf)
    # Run model compression toolkit
    # quantized_model, quantization_info = quant.quantize(float_model,
    #                                                     ml.get_representative_dataset,
    #                                                     kpi,
    #                                                     my_core_config,
    #                                                     target_platform_cap,
    #                                                     config)
   # qc = mct.core.QuantizationErrorMethod.args.quantization_method
    
    quantization_method = args.quantization_method.upper() 
    weights_error_method = mct.core.QuantizationErrorMethod[quantization_method]
    quantization_config = mct.core.QuantizationConfig(activation_error_method=mct.core.QuantizationErrorMethod.MSE,weights_error_method=weights_error_method)
    configuration = mct.core.CoreConfig(quantization_config,mixed_precision_config=mct.core.MixedPrecisionQuantizationConfigV2(num_of_images=args.mixed_precision_num_of_images))

    # Get a TargetPlatformCapabilities object that models the hardware for the quantized model inference.
    # Here, for example, we use the default platform that is attached to a Tensorflow layers representation.
    target_platform_cap = mct.get_target_platform_capabilities('tensorflow', 'default')

    kpi_data = mct.core.keras_kpi_data_experimental(float_model,
                                                    ml.get_representative_dataset(representative_dataset_folder = '/data1/work/Ming/MCT/dataset/imagenet/ILSVRC2012_img_test_v10102019/', n_iter=1, batch_size= 2),
                                                    configuration,
                                                    target_platform_capabilities=target_platform_cap)


    kpi = mct.core.KPI(kpi_data.weights_memory * args.weights_compression_ratio)

    quantized_model, quantization_info = mct.ptq.keras_post_training_quantization_experimental(float_model,
                                                                                               ml.get_representative_dataset(representative_dataset_folder = '/data1/work/Ming/MCT/dataset/imagenet/ILSVRC2012_img_test_v10102019/', n_iter=1, batch_size= 2),
                                                                                               target_kpi=kpi,
                                                                                               core_config=configuration,
                                                                                               target_platform_capabilities=target_platform_cap)
```

**Comment by ofirgo** [comment] 2024-03-26 14:02
Hi @Ming-Ivy ,

Your observation is correct. The number of samples in the representative dataset, which MCT uses to collect statistics, equals n_iters x batch_size.

Regarding your questions:

1. MCT doesn't add any randomization to the data when collecting statistics or running mixed precision. It simply iterating over the provided representative dataset generator. If randomization is implemented within the generator, it will be executed.

2. Generally, more samples tend to improve accuracy, but there are cases where adding samples can negatively affect quantization. For example, if the added samples have extreme features that don't represent the true distribution of the dataset.

3. It's not a bug. If the representative dataset doesn't have enough samples, MCT will run mixed precision with fewer samples than requested. You should see a warning message in the logs indicating this ("Not enough images in representative dataset to generate").

Please let me know if you have any other questions regarding this subject.

**Comment by ofirgo** [comment] 2024-04-07 10:27
ince there haven't been any recent updates or responses, I'm closing this thread. If you encounter any further issues or have additional questions regarding this topic, please feel free to reopen the issue.

**Closed by ofirgo** 2024-04-07 10:27 UTC
Labels: help wanted
